# Generated by Django 5.0.3 on 2024-03-23 05:57

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="timing",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
